import { Stamp, StampList } from "types";

export const defaultStamp: Stamp = {
    title: "#emotwicon",
    name: "emotwicon",
    ext: "png",
    fullpath: "emotwicon.png",
    author: "m19e",
};

export const stampList: StampList = {
    natsuha_delicious: {
        title: "おいしいわ!!",
        name: "natsuha_delicious",
        ext: "png",
        fullpath: "natsuha_delicious.png",
        author: "noe_aoikaba",
    },
    kiriko_dayoff_fix: {
        title: "お休みにしたほうがいいと思うんです…!!",
        name: "kiriko_dayoff_fix",
        ext: "png",
        fullpath: "kiriko_dayoff_fix.png",
        author: "noe_aoikaba",
    },
    yuika_onaroll: {
        title: "ただいま絶好調で～す!!",
        name: "yuika_onaroll",
        ext: "PNG",
        fullpath: "yuika_onaroll.PNG",
        author: "noe_aoikaba",
    },

    tenka_holiday: {
        title: "今日はお休み",
        name: "tenka_holiday",
        ext: "jpg",
        fullpath: "tenka_holiday.jpg",
        author: "shibainuMk_2",
    },
    asakaho_gogo: {
        title: "GOGO!",
        name: "asakaho_gogo",
        ext: "jpg",
        fullpath: "asakaho_gogo.jpg",
        author: "shibainuMk_2",
    },
    nichika_muki: {
        title: "ムッキムキなので！",
        name: "nichika_muki",
        ext: "jpg",
        fullpath: "nichika_muki.jpg",
        author: "shibainuMk_2",
    },
    nichika_mukimuki: {
        title: "むきむき!",
        name: "nichika_mukimuki",
        ext: "jpg",
        fullpath: "nichika_mukimuki.jpg",
        author: "_daaako_",
    },
    nichika_bank: {
        title: "っっ",
        name: "nichika_bank",
        ext: "jpg",
        fullpath: "nichika_bank.jpg",
        author: "_eruru0x0_",
    },
    mikoto_sure: {
        title: "いいよ",
        name: "mikoto_sure",
        ext: "png",
        fullpath: "mikoto_sure.png",
        author: "gomame_rabbit",
    },
    juri_lgtm: {
        title: "いいんじゃねーか？",
        name: "juri_lgtm",
        ext: "png",
        fullpath: "juri_lgtm.png",
        author: "gomame_rabbit",
    },
    luca_sickness: {
        title: "病んだ",
        name: "luca_sickness",
        ext: "png",
        fullpath: "luca_sickness.png",
        author: "o0w0l",
    },
    mamimi_donmai: {
        title: "どんまぁい",
        name: "mamimi_donmai",
        ext: "png",
        fullpath: "mamimi_donmai.png",
        author: "o0w0l",
    },
    thinking_koito: {
        title: "thinking_koito",
        name: "thinking_koito",
        ext: "png",
        fullpath: "thinking_koito.png",
        author: "o0w0l",
    },
    mano_howa: {
        title: "ほわ～っ♡",
        name: "mano_howa",
        ext: "png",
        fullpath: "mano_howa.png",
        author: "DELU_shinybald",
    },
    nekomine_night: {
        title: "オヤスミネ",
        name: "nekomine_night",
        ext: "jpg",
        fullpath: "nekomine_night.jpg",
        author: "Tight_Shiva",
    },
    madoka_morning: {
        title: "おはようございます",
        name: "madoka_morning",
        ext: "jpg",
        fullpath: "madoka_morning.jpg",
        author: "cy__ms",
    },
    koito_yeah: {
        title: "YEAH!",
        name: "koito_yeah",
        ext: "png",
        fullpath: "koito_yeah.png",
        author: "watamotenoika",
    },
    natsuha_bravo: {
        title: "ブラボーよ！",
        name: "natsuha_bravo",
        ext: "png",
        fullpath: "natsuha_bravo.png",
        author: "o0w0l",
    },
    kaho_sugoi: {
        title: "スゴいです！",
        name: "kaho_sugoi",
        ext: "png",
        fullpath: "kaho_sugoi.png",
        author: "o0w0l",
    },
    chiyoko_gyoi: {
        title: "御意",
        name: "chiyoko_gyoi",
        ext: "png",
        fullpath: "chiyoko_gyoi.png",
        author: "o0w0l",
    },
    rinze_narimasita: {
        title: "成りました。",
        name: "rinze_narimasita",
        ext: "png",
        fullpath: "rinze_narimasita.png",
        author: "o0w0l",
    },
    asahi_gotit: {
        title: "わかったっす",
        name: "asahi_gotit",
        ext: "png",
        fullpath: "asahi_gotit.png",
        author: "NPspencerHG",
    },
    fuyuko_what: {
        title: "何！？",
        name: "fuyuko_what",
        ext: "jpg",
        fullpath: "fuyuko_what.jpg",
        author: "NPspencerHG",
    },
    koito_pyaa: {
        title: "ぴゃ～",
        name: "koito_pyaa",
        ext: "png",
        fullpath: "koito_pyaa.png",
        author: "NPspencerHG",
    },
    nichika_peka: {
        title: "ぺかー。",
        name: "nichika_peka",
        ext: "png",
        fullpath: "nichika_peka.png",
        author: "NPspencerHG",
    },
    chiyoko_arrest: {
        title: "たいほ！",
        name: "chiyoko_arrest",
        ext: "png",
        fullpath: "chiyoko_arrest.png",
        author: "murisuu_yaha",
    },
    rinze_foul: {
        title: "反則でございます。",
        name: "rinze_foul",
        ext: "png",
        fullpath: "rinze_foul.png",
        author: "murisuu_yaha",
    },
    amtn_sweet: {
        title: "やった～!!",
        name: "amtn_sweet",
        ext: "png",
        fullpath: "amtn_sweet.png",
        author: "yamato_cogane",
    },
    askr_nice: {
        title: "いいね",
        name: "askr_nice",
        ext: "png",
        fullpath: "askr_nice.png",
        author: "wa_jwa_jpon2",
    },
    askr_help: {
        title: "わからん",
        name: "askr_help",
        ext: "png",
        fullpath: "askr_help.png",
        author: "wa_jwa_jpon2",
    },
    askr_hgcsorry: {
        title: "ごめん樋口",
        name: "askr_hgcsorry",
        ext: "png",
        fullpath: "askr_hgcsorry.png",
        author: "wa_jwa_jpon2",
    },
    hgc_oko: {
        title: "は？",
        name: "hgc_oko",
        ext: "png",
        fullpath: "hgc_oko.png",
        author: "wa_jwa_jpon2",
    },
    hgc_sigh: {
        title: "はぁ…",
        name: "hgc_sigh",
        ext: "png",
        fullpath: "hgc_sigh.png",
        author: "wa_jwa_jpon2",
    },
    hgc_empty: {
        title: "中身のない会話",
        name: "hgc_empty",
        ext: "png",
        fullpath: "hgc_empty.png",
        author: "wa_jwa_jpon2",
    },
    hgc_greatkit: {
        title: "偉い、小糸",
        name: "hgc_greatkit",
        ext: "png",
        fullpath: "hgc_greatkit.png",
        author: "wa_jwa_jpon2",
    },
    kit_no: {
        title: "ダメだよっ！",
        name: "kit_no",
        ext: "png",
        fullpath: "kit_no.png",
        author: "wa_jwa_jpon2",
    },
    kit_pya: {
        title: "ぴゃ…！",
        name: "kit_pya",
        ext: "png",
        fullpath: "kit_pya.png",
        author: "wa_jwa_jpon2",
    },
    kit_yoyu: {
        title: "よゆーです！",
        name: "kit_yoyu",
        ext: "png",
        fullpath: "kit_yoyu.png",
        author: "wa_jwa_jpon2",
    },
    hnn_aha: {
        title: "あはー？",
        name: "hnn_aha",
        ext: "png",
        fullpath: "hnn_aha.png",
        author: "wa_jwa_jpon2",
    },
    hnn_yaha: {
        title: "やは～♡",
        name: "hnn_yaha",
        ext: "png",
        fullpath: "hnn_yaha.png",
        author: "wa_jwa_jpon2",
    },
    hnn_complain: {
        title: "え～？",
        name: "hnn_complain",
        ext: "png",
        fullpath: "hnn_complain.png",
        author: "wa_jwa_jpon2",
    },
    cyk_gyudon: {
        title: "わぁ！牛丼！",
        name: "cyk_gyudon",
        ext: "jpg",
        fullpath: "cyk_gyudon.jpg",
        author: "tukumo_ugo",
    },
    rin_fuun: {
        title: "ふーん",
        name: "rin_fuun",
        ext: "png",
        fullpath: "rin_fuun.png",
        author: "FiV7KhbogVC",
    },
    chiihaya_default: {
        title: "み",
        name: "chiihaya_default",
        ext: "PNG",
        fullpath: "chiihaya_default.PNG",
        author: "kanadechankawai",
    },
    chiihaya_nod: {
        title: "み",
        name: "chiihaya_nod",
        ext: "PNG",
        fullpath: "chiihaya_nod.PNG",
        author: "kanadechankawai",
    },
    chiihaya_what: {
        title: "み？",
        name: "chiihaya_what",
        ext: "PNG",
        fullpath: "chiihaya_what.PNG",
        author: "kanadechankawai",
    },
    chiihaya_fume: {
        title: "み",
        name: "chiihaya_fume",
        ext: "PNG",
        fullpath: "chiihaya_fume.PNG",
        author: "kanadechankawai",
    },
    chiihaya_glitter: {
        title: "み",
        name: "chiihaya_glitter",
        ext: "PNG",
        fullpath: "chiihaya_glitter.PNG",
        author: "kanadechankawai",
    },
    chiihaya_wow: {
        title: "み",
        name: "chiihaya_wow",
        ext: "PNG",
        fullpath: "chiihaya_wow.PNG",
        author: "kanadechankawai",
    },
    jelkun_je: {
        title: "じぇ～",
        name: "jelkun_je",
        ext: "jpg",
        fullpath: "jelkun_je.jpg",
        author: "FiV7KhbogVC",
    },
    wani_goodnight: {
        title: "Good Night",
        name: "wani_goodnight",
        ext: "png",
        fullpath: "wani_goodnight.png",
        author: "ulzoll",
    },
};

export const JKstampList: StampList = {
    yomotsu_near: {
        title: "!!!",
        name: "yomotsu_near",
        ext: "png",
        fullpath: "jk/yomotsu_near.png",
        author: "ameno_tokotachi",
    },
    yomotsu_night: {
        title: "おやすみ！",
        name: "yomotsu_night",
        ext: "png",
        fullpath: "jk/yomotsu_night.png",
        author: "ameno_tokotachi",
    },
    yomotsu_morning: {
        title: "おはよう！",
        name: "yomotsu_morning",
        ext: "png",
        fullpath: "jk/yomotsu_morning.png",
        author: "ameno_tokotachi",
    },
    yomotsu_whistle: {
        title: "ピピ～ッ！",
        name: "yomotsu_whistle",
        ext: "png",
        fullpath: "jk/yomotsu_whistle.png",
        author: "ameno_tokotachi",
    },
    yomotsu_mmm: {
        title: "ムーー",
        name: "yomotsu_mmm",
        ext: "png",
        fullpath: "jk/yomotsu_mmm.png",
        author: "ameno_tokotachi",
    },
    flare_blush: {
        title: "あわわわわわわわわ",
        name: "flare_blush",
        ext: "png",
        fullpath: "jk/flare_blush.png",
        author: "Flame_tsukushi4",
    },
    flare_ew: {
        title: "う゛……",
        name: "flare_ew",
        ext: "png",
        fullpath: "jk/flare_ew.png",
        author: "Flame_tsukushi4",
    },
    ishima_clean_color: {
        title: "部屋片付けて。",
        name: "ishima_clean_color",
        ext: "png",
        fullpath: "jk/ishima_clean_color.png",
        author: "",
    },
    ishima_fufu_color: {
        title: "フフッ",
        name: "ishima_fufu_color",
        ext: "png",
        fullpath: "jk/ishima_fufu_color.png",
        author: "",
    },
    ishima_sun_color: {
        title: "ｽﾝ",
        name: "ishima_sun_color",
        ext: "png",
        fullpath: "jk/ishima_sun_color.png",
        author: "",
    },
    taoru_deny_color: {
        title: "ちがうんですよ",
        name: "taoru_deny_color",
        ext: "png",
        fullpath: "jk/taoru_deny_color.png",
        author: "",
    },
    taoru_nandayo_color: {
        title: "なんだよぉ…",
        name: "taoru_nandayo_color",
        ext: "png",
        fullpath: "jk/taoru_nandayo_color.png",
        author: "",
    },
    taoru_regression_color: {
        title: "おぎゃあおぎゃあ",
        name: "taoru_regression_color",
        ext: "png",
        fullpath: "jk/taoru_regression_color.png",
        author: "",
    },
    me_flarechan_color: {
        title: "ふれあちゃん？",
        name: "me_flarechan_color",
        ext: "png",
        fullpath: "jk/me_flarechan_color.png",
        author: "",
    },
    me_straight_color: {
        title: "ツッコまんからなっ",
        name: "me_straight_color",
        ext: "png",
        fullpath: "jk/me_straight_color.png",
        author: "",
    },
    me_sleep_color: {
        title: "寝な。",
        name: "me_sleep_color",
        ext: "png",
        fullpath: "jk/me_sleep_color.png",
        author: "",
    },
    // ishima_clean: {
    //     title: "部屋片付けて。",
    //     name: "ishima_clean",
    //     ext: "jpg",
    //     fullpath: "jk/ishima_clean.jpg",
    //     author: "",
    // },
    // ishima_fufu: {
    //     title: "フフッ",
    //     name: "ishima_fufu",
    //     ext: "jpg",
    //     fullpath: "jk/ishima_fufu.jpg",
    //     author: "",
    // },
    // ishima_sun: {
    //     title: "ｽﾝ",
    //     name: "ishima_sun",
    //     ext: "jpg",
    //     fullpath: "jk/ishima_sun.jpg",
    //     author: "",
    // },
    // taoru_deny: {
    //     title: "ちがうんですよ",
    //     name: "taoru_deny",
    //     ext: "jpg",
    //     fullpath: "jk/taoru_deny.jpg",
    //     author: "",
    // },
    // taoru_nandayo: {
    //     title: "なんだよぉ…",
    //     name: "taoru_nandayo",
    //     ext: "jpg",
    //     fullpath: "jk/taoru_nandayo.jpg",
    //     author: "",
    // },
    // me_flarechan: {
    //     title: "ふれあちゃん？",
    //     name: "me_flarechan",
    //     ext: "jpg",
    //     fullpath: "jk/me_flarechan.jpg",
    //     author: "",
    // },
    // me_straight: {
    //     title: "ツッコまんからなっ",
    //     name: "me_straight",
    //     ext: "jpg",
    //     fullpath: "jk/me_straight.jpg",
    //     author: "",
    // },
    // me_sleep: {
    //     title: "寝な。",
    //     name: "me_sleep",
    //     ext: "jpg",
    //     fullpath: "jk/me_sleep.jpg",
    //     author: "",
    // },
};
