import { Stamp, StampList } from "types";

export const defaultStamp: Stamp = {
    title: "#emotwicon",
    name: "emotwicon",
    ext: "png",
    fullpath: "emotwicon.png",
    author: "m19e",
};

export const stampList: StampList = {
    askr_nice: {
        title: "いいね",
        name: "askr_nice",
        ext: "png",
        fullpath: "askr_nice.png",
        author: "wa_jwa_jpon2",
    },
    askr_help: {
        title: "わからん",
        name: "askr_help",
        ext: "png",
        fullpath: "askr_help.png",
        author: "wa_jwa_jpon2",
    },
    askr_hgcsorry: {
        title: "ごめん樋口",
        name: "askr_hgcsorry",
        ext: "png",
        fullpath: "askr_hgcsorry.png",
        author: "wa_jwa_jpon2",
    },
    hgc_oko: {
        title: "は？",
        name: "hgc_oko",
        ext: "png",
        fullpath: "hgc_oko.png",
        author: "wa_jwa_jpon2",
    },
    hgc_sigh: {
        title: "はぁ…",
        name: "hgc_sigh",
        ext: "png",
        fullpath: "hgc_sigh.png",
        author: "wa_jwa_jpon2",
    },
    hgc_empty: {
        title: "中身のない会話",
        name: "hgc_empty",
        ext: "png",
        fullpath: "hgc_empty.png",
        author: "wa_jwa_jpon2",
    },
    hgc_greatkit: {
        title: "偉い、小糸",
        name: "hgc_greatkit",
        ext: "png",
        fullpath: "hgc_greatkit.png",
        author: "wa_jwa_jpon2",
    },
    kit_no: {
        title: "ダメだよっ！",
        name: "kit_no",
        ext: "png",
        fullpath: "kit_no.png",
        author: "wa_jwa_jpon2",
    },
    kit_pya: {
        title: "ぴゃ…！",
        name: "kit_pya",
        ext: "png",
        fullpath: "kit_pya.png",
        author: "wa_jwa_jpon2",
    },
    kit_yoyu: {
        title: "よゆーです！",
        name: "kit_yoyu",
        ext: "png",
        fullpath: "kit_yoyu.png",
        author: "wa_jwa_jpon2",
    },
    hnn_aha: {
        title: "あはー？",
        name: "hnn_aha",
        ext: "png",
        fullpath: "hnn_aha.png",
        author: "wa_jwa_jpon2",
    },
    hnn_yaha: {
        title: "やは～♡",
        name: "hnn_yaha",
        ext: "png",
        fullpath: "hnn_yaha.png",
        author: "wa_jwa_jpon2",
    },
    hnn_complain: {
        title: "え～？",
        name: "hnn_complain",
        ext: "png",
        fullpath: "hnn_complain.png",
        author: "wa_jwa_jpon2",
    },
};

export const JKstampList: StampList = {
    me_flarechan_color: {
        title: "ふれあちゃん？",
        name: "me_flarechan_color",
        ext: "png",
        fullpath: "jk/me_flarechan_color.png",
        author: "",
    },
    me_straight_color: {
        title: "ツッコまんからなっ",
        name: "me_straight_color",
        ext: "png",
        fullpath: "jk/me_straight_color.png",
        author: "",
    },
    me_sleep_color: {
        title: "寝な。",
        name: "me_sleep_color",
        ext: "png",
        fullpath: "jk/me_sleep_color.png",
        author: "",
    },
    ishima_clean: {
        title: "部屋片付けて。",
        name: "ishima_clean",
        ext: "jpg",
        fullpath: "jk/ishima_clean.jpg",
        author: "",
    },
    ishima_fufu: {
        title: "フフッ",
        name: "ishima_fufu",
        ext: "jpg",
        fullpath: "jk/ishima_fufu.jpg",
        author: "",
    },
    ishima_sun: {
        title: "ｽﾝ",
        name: "ishima_sun",
        ext: "jpg",
        fullpath: "jk/ishima_sun.jpg",
        author: "",
    },
    taoru_deny: {
        title: "ちがうんですよ",
        name: "taoru_deny",
        ext: "jpg",
        fullpath: "jk/taoru_deny.jpg",
        author: "",
    },
    taoru_nandayo: {
        title: "なんだよぉ…",
        name: "taoru_nandayo",
        ext: "jpg",
        fullpath: "jk/taoru_nandayo.jpg",
        author: "",
    },
    me_flarechan: {
        title: "ふれあちゃん？",
        name: "me_flarechan",
        ext: "jpg",
        fullpath: "jk/me_flarechan.jpg",
        author: "",
    },
    me_straight: {
        title: "ツッコまんからなっ",
        name: "me_straight",
        ext: "jpg",
        fullpath: "jk/me_straight.jpg",
        author: "",
    },
    me_sleep: {
        title: "寝な。",
        name: "me_sleep",
        ext: "jpg",
        fullpath: "jk/me_sleep.jpg",
        author: "",
    },
};
