import { Stamp, StampList } from "types";

export const defaultStamp: Stamp = {
    title: "#emotwicon",
    name: "emotwicon",
    ext: "png",
    fullpath: "emotwicon.png",
    author: "m19e",
};

export const stampList: StampList = {
    yuika_onaroll: {
        title: "ただいま絶好調で～す!!",
        name: "yuika_onaroll",
        ext: "PNG",
        fullpath: "yuika_onaroll.PNG",
        author: "noe_aoikaba",
    },
    kiriko_dayoff: {
        title: "お休みにしたほうがいいと思うんです…!!",
        name: "kiriko_dayoff",
        ext: "PNG",
        fullpath: "kiriko_dayoff.PNG",
        author: "noe_aoikaba",
    },
    natsuha_bravo: {
        title: "ブラボーよ！",
        name: "natsuha_bravo",
        ext: "png",
        fullpath: "natsuha_bravo.png",
        author: "o0w0l",
    },
    kaho_sugoi: {
        title: "スゴいです！",
        name: "kaho_sugoi",
        ext: "png",
        fullpath: "kaho_sugoi.png",
        author: "o0w0l",
    },
    chiyoko_gyoi: {
        title: "御意",
        name: "chiyoko_gyoi",
        ext: "png",
        fullpath: "chiyoko_gyoi.png",
        author: "o0w0l",
    },
    rinze_narimasita: {
        title: "成りました。",
        name: "rinze_narimasita",
        ext: "png",
        fullpath: "rinze_narimasita.png",
        author: "o0w0l",
    },
    koito_yeah: {
        title: "YEAH!",
        name: "koito_yeah",
        ext: "png",
        fullpath: "koito_yeah.png",
        author: "watamotenoika",
    },
    asahi_gotit: {
        title: "わかったっす",
        name: "asahi_gotit",
        ext: "png",
        fullpath: "asahi_gotit.png",
        author: "NPspencerHG",
    },
    koito_pyaa: {
        title: "ぴゃ～",
        name: "koito_pyaa",
        ext: "png",
        fullpath: "koito_pyaa.png",
        author: "NPspencerHG",
    },
    nichika_peka: {
        title: "ぺかー。",
        name: "nichika_peka",
        ext: "png",
        fullpath: "nichika_peka.png",
        author: "NPspencerHG",
    },
    amtn_sweet: {
        title: "やった～!!",
        name: "amtn_sweet",
        ext: "png",
        fullpath: "amtn_sweet.png",
        author: "yamato_cogane",
    },
    rinze_foul: {
        title: "反則でございます。",
        name: "rinze_foul",
        ext: "png",
        fullpath: "rinze_foul.png",
        author: "murisuu_yaha",
    },
    chiyoko_arrest: {
        title: "たいほ！",
        name: "chiyoko_arrest",
        ext: "png",
        fullpath: "chiyoko_arrest.png",
        author: "murisuu_yaha",
    },
    askr_nice: {
        title: "いいね",
        name: "askr_nice",
        ext: "png",
        fullpath: "askr_nice.png",
        author: "wa_jwa_jpon2",
    },
    askr_help: {
        title: "わからん",
        name: "askr_help",
        ext: "png",
        fullpath: "askr_help.png",
        author: "wa_jwa_jpon2",
    },
    askr_hgcsorry: {
        title: "ごめん樋口",
        name: "askr_hgcsorry",
        ext: "png",
        fullpath: "askr_hgcsorry.png",
        author: "wa_jwa_jpon2",
    },
    hgc_oko: {
        title: "は？",
        name: "hgc_oko",
        ext: "png",
        fullpath: "hgc_oko.png",
        author: "wa_jwa_jpon2",
    },
    hgc_sigh: {
        title: "はぁ…",
        name: "hgc_sigh",
        ext: "png",
        fullpath: "hgc_sigh.png",
        author: "wa_jwa_jpon2",
    },
    hgc_empty: {
        title: "中身のない会話",
        name: "hgc_empty",
        ext: "png",
        fullpath: "hgc_empty.png",
        author: "wa_jwa_jpon2",
    },
    hgc_greatkit: {
        title: "偉い、小糸",
        name: "hgc_greatkit",
        ext: "png",
        fullpath: "hgc_greatkit.png",
        author: "wa_jwa_jpon2",
    },
    kit_no: {
        title: "ダメだよっ！",
        name: "kit_no",
        ext: "png",
        fullpath: "kit_no.png",
        author: "wa_jwa_jpon2",
    },
    kit_pya: {
        title: "ぴゃ…！",
        name: "kit_pya",
        ext: "png",
        fullpath: "kit_pya.png",
        author: "wa_jwa_jpon2",
    },
    kit_yoyu: {
        title: "よゆーです！",
        name: "kit_yoyu",
        ext: "png",
        fullpath: "kit_yoyu.png",
        author: "wa_jwa_jpon2",
    },
    hnn_aha: {
        title: "あはー？",
        name: "hnn_aha",
        ext: "png",
        fullpath: "hnn_aha.png",
        author: "wa_jwa_jpon2",
    },
    hnn_yaha: {
        title: "やは～♡",
        name: "hnn_yaha",
        ext: "png",
        fullpath: "hnn_yaha.png",
        author: "wa_jwa_jpon2",
    },
    hnn_complain: {
        title: "え～？",
        name: "hnn_complain",
        ext: "png",
        fullpath: "hnn_complain.png",
        author: "wa_jwa_jpon2",
    },
    cyk_gyudon: {
        title: "わぁ！牛丼！",
        name: "cyk_gyudon",
        ext: "jpg",
        fullpath: "cyk_gyudon.jpg",
        author: "tukumo_ugo",
    },
    rin_fuun: {
        title: "ふーん",
        name: "rin_fuun",
        ext: "png",
        fullpath: "rin_fuun.png",
        author: "FiV7KhbogVC",
    },
    chiihaya_default: {
        title: "み",
        name: "chiihaya_default",
        ext: "PNG",
        fullpath: "chiihaya_default.PNG",
        author: "kanadechankawai",
    },
    chiihaya_nod: {
        title: "み",
        name: "chiihaya_nod",
        ext: "PNG",
        fullpath: "chiihaya_nod.PNG",
        author: "kanadechankawai",
    },
    chiihaya_what: {
        title: "み？",
        name: "chiihaya_what",
        ext: "PNG",
        fullpath: "chiihaya_what.PNG",
        author: "kanadechankawai",
    },
    chiihaya_fume: {
        title: "み",
        name: "chiihaya_fume",
        ext: "PNG",
        fullpath: "chiihaya_fume.PNG",
        author: "kanadechankawai",
    },
    chiihaya_glitter: {
        title: "み",
        name: "chiihaya_glitter",
        ext: "PNG",
        fullpath: "chiihaya_glitter.PNG",
        author: "kanadechankawai",
    },
    chiihaya_wow: {
        title: "み",
        name: "chiihaya_wow",
        ext: "PNG",
        fullpath: "chiihaya_wow.PNG",
        author: "kanadechankawai",
    },
    jelkun_je: {
        title: "じぇ～",
        name: "jelkun_je",
        ext: "jpg",
        fullpath: "jelkun_je.jpg",
        author: "FiV7KhbogVC",
    },
    wani_goodnight: {
        title: "Good Night",
        name: "wani_goodnight",
        ext: "png",
        fullpath: "wani_goodnight.png",
        author: "ulzoll",
    },
};

export const JKstampList: StampList = {
    yomotsu_morning: {
        title: "おはよう！",
        name: "yomotsu_morning",
        ext: "png",
        fullpath: "jk/yomotsu_morning.png",
        author: "ameno_tokotachi",
    },
    yomotsu_whistle: {
        title: "ピピ～ッ！",
        name: "yomotsu_whistle",
        ext: "png",
        fullpath: "jk/yomotsu_whistle.png",
        author: "ameno_tokotachi",
    },
    yomotsu_mmm: {
        title: "ムーー",
        name: "yomotsu_mmm",
        ext: "png",
        fullpath: "jk/yomotsu_mmm.png",
        author: "ameno_tokotachi",
    },
    flare_blush: {
        title: "あわわわわわわわわ",
        name: "flare_blush",
        ext: "png",
        fullpath: "jk/flare_blush.png",
        author: "Flame_tsukushi4",
    },
    flare_ew: {
        title: "う゛……",
        name: "flare_ew",
        ext: "png",
        fullpath: "jk/flare_ew.png",
        author: "Flame_tsukushi4",
    },
    ishima_clean_color: {
        title: "部屋片付けて。",
        name: "ishima_clean_color",
        ext: "png",
        fullpath: "jk/ishima_clean_color.png",
        author: "",
    },
    ishima_fufu_color: {
        title: "フフッ",
        name: "ishima_fufu_color",
        ext: "png",
        fullpath: "jk/ishima_fufu_color.png",
        author: "",
    },
    ishima_sun_color: {
        title: "ｽﾝ",
        name: "ishima_sun_color",
        ext: "png",
        fullpath: "jk/ishima_sun_color.png",
        author: "",
    },
    taoru_deny_color: {
        title: "ちがうんですよ",
        name: "taoru_deny_color",
        ext: "png",
        fullpath: "jk/taoru_deny_color.png",
        author: "",
    },
    taoru_nandayo_color: {
        title: "なんだよぉ…",
        name: "taoru_nandayo_color",
        ext: "png",
        fullpath: "jk/taoru_nandayo_color.png",
        author: "",
    },
    taoru_regression_color: {
        title: "おぎゃあおぎゃあ",
        name: "taoru_regression_color",
        ext: "png",
        fullpath: "jk/taoru_regression_color.png",
        author: "",
    },
    me_flarechan_color: {
        title: "ふれあちゃん？",
        name: "me_flarechan_color",
        ext: "png",
        fullpath: "jk/me_flarechan_color.png",
        author: "",
    },
    me_straight_color: {
        title: "ツッコまんからなっ",
        name: "me_straight_color",
        ext: "png",
        fullpath: "jk/me_straight_color.png",
        author: "",
    },
    me_sleep_color: {
        title: "寝な。",
        name: "me_sleep_color",
        ext: "png",
        fullpath: "jk/me_sleep_color.png",
        author: "",
    },
    // ishima_clean: {
    //     title: "部屋片付けて。",
    //     name: "ishima_clean",
    //     ext: "jpg",
    //     fullpath: "jk/ishima_clean.jpg",
    //     author: "",
    // },
    // ishima_fufu: {
    //     title: "フフッ",
    //     name: "ishima_fufu",
    //     ext: "jpg",
    //     fullpath: "jk/ishima_fufu.jpg",
    //     author: "",
    // },
    // ishima_sun: {
    //     title: "ｽﾝ",
    //     name: "ishima_sun",
    //     ext: "jpg",
    //     fullpath: "jk/ishima_sun.jpg",
    //     author: "",
    // },
    // taoru_deny: {
    //     title: "ちがうんですよ",
    //     name: "taoru_deny",
    //     ext: "jpg",
    //     fullpath: "jk/taoru_deny.jpg",
    //     author: "",
    // },
    // taoru_nandayo: {
    //     title: "なんだよぉ…",
    //     name: "taoru_nandayo",
    //     ext: "jpg",
    //     fullpath: "jk/taoru_nandayo.jpg",
    //     author: "",
    // },
    // me_flarechan: {
    //     title: "ふれあちゃん？",
    //     name: "me_flarechan",
    //     ext: "jpg",
    //     fullpath: "jk/me_flarechan.jpg",
    //     author: "",
    // },
    // me_straight: {
    //     title: "ツッコまんからなっ",
    //     name: "me_straight",
    //     ext: "jpg",
    //     fullpath: "jk/me_straight.jpg",
    //     author: "",
    // },
    // me_sleep: {
    //     title: "寝な。",
    //     name: "me_sleep",
    //     ext: "jpg",
    //     fullpath: "jk/me_sleep.jpg",
    //     author: "",
    // },
};
